In [28]:
import numpy as np # linear algebra  
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os # to use operating system dependent functionality
#run following commands to install librosa module for anaconda for first time
#conda install -c numba numba
#conda install -c conda-forge librosa
import librosa # to extract speech features
import librosa.display #to display audio as wave plot, spectrogram, or colormap
import wave # read and write WAV files
#run following commands to install soundfile module for anaconda for first time
#conda install -c conda-forge pysoundfile
import soundfile
import matplotlib.pyplot as plt # to generate the visualizations
import random # to shuffle the train and test data
import glob
# MLP Classifier
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report #classification report
from sklearn.metrics import confusion_matrix #confusion matrix
from sklearn.model_selection import cross_val_score
import pickle as pkl

In [31]:
#rom sklearn.externals import joblib

In [3]:
f_x=open('x.npy','rb')
x=np.load(f_x)
f_y=open('y.npy','rb')
y=np.load(f_y)

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [32]:
x_train

array([[-5.31651428e+02,  7.78657303e+01,  2.15921040e+01, ...,
         4.61868286e-01,  5.27371466e-01,  4.13227230e-01],
       [-5.80325989e+02,  6.28923492e+01, -5.56045103e+00, ...,
         6.42150939e-01,  5.76573670e-01,  6.01093471e-01],
       [-6.28379395e+02,  5.30089417e+01, -1.34875357e+00, ...,
         6.78749919e-01,  7.12219477e-01,  7.40691304e-01],
       ...,
       [-6.13740723e+02,  4.59259186e+01, -2.03450546e+01, ...,
         5.55046499e-01,  4.83037293e-01,  4.56697702e-01],
       [-4.14405823e+02,  6.29957924e+01,  9.83915865e-01, ...,
         5.74915707e-01,  4.89906162e-01,  5.50389230e-01],
       [-6.26350830e+02,  6.13934631e+01, -1.43732004e+01, ...,
         7.18461096e-01,  7.24123359e-01,  6.90424502e-01]])

In [33]:
y_train

array(['sad', 'fearful', 'angry', ..., 'calm', 'disgust', 'sad'],
      dtype='<U9')

In [5]:
model_mlp=MLPClassifier(alpha=0.01,batch_size=100,epsilon=1e-08,hidden_layer_sizes=(180,180),learning_rate='adaptive',max_iter=400)

In [6]:
model_mlp.fit(x_train,y_train)

MLPClassifier(alpha=0.01, batch_size=100, hidden_layer_sizes=(180, 180),
              learning_rate='adaptive', max_iter=400)

In [7]:
y_pred_test=model_mlp.predict(x_test)
y_pred_train=model_mlp.predict(x_train)

In [8]:
accuracy1=accuracy_score(y_true=y_test,y_pred=y_pred_test)
accuracy2=accuracy_score(y_true=y_train,y_pred=y_pred_train)
print("Test Accuracy:{:.2f}%".format(accuracy1*100))
print("Train Accuracy:{:.2f}%".format(accuracy2*100))

Test Accuracy:85.63%
Train Accuracy:90.91%


In [9]:
cv_results = cross_val_score(model_mlp, x_train, y_train,scoring='accuracy', cv = 5)
print(cv_results)
print("Avg accuracy:",cv_results.mean()*100)

[0.83590963 0.8        0.81785714 0.81904762 0.81904762]
Avg accuracy: 81.83724024687163


In [17]:
#classification report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

       angry       0.82      0.91      0.86       171
        calm       0.67      0.87      0.76        54
     disgust       0.85      0.88      0.86       127
     fearful       0.86      0.88      0.87       163
       happy       0.92      0.84      0.88       157
     neutral       0.91      0.84      0.87       100
         sad       0.81      0.85      0.83       150
   surprised       0.97      0.77      0.86       129

    accuracy                           0.86      1051
   macro avg       0.85      0.85      0.85      1051
weighted avg       0.86      0.86      0.86      1051



In [18]:
#confusion matrix
cm = confusion_matrix(y_test,y_pred_test)
print(cm)

[[155   0   9   5   1   1   0   0]
 [  0  47   0   0   2   1   4   0]
 [  5   3 112   1   1   0   3   2]
 [ 10   0   1 144   2   1   4   1]
 [ 10   4   1   5 132   1   4   0]
 [  1   8   0   0   0  84   7   0]
 [  2   5   2  11   1   2 127   0]
 [  6   3   7   1   4   2   7  99]]


In [1]:
joblib.dump(model_mlp, 'mlp_model.pkl') 
print("MODEL SAVED")

NameError: name 'joblib' is not defined